apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: qmessentials
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: qmessentials
      service: auth
  template:
    metadata:
      labels:
        app: qmessentials
        service: auth
    spec:
      containers:
      - name: qmessentials-auth
        image: qmessentials/auth:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3010
        env:
        - name: PORT
          value: "3010"  # Set the port the app should listen on
