apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-postgres-pv
  namespace: qmessentials
spec:
  capacity:
    storage: 1Gi  # Change this as needed
  accessModes:
    - ReadWriteOnce
  hostPath:  # For local testing
    path: /usr/local/data/k8s-pvs/qmessentials-auth
