apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: qmessentials
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.containerPort }}       # Port accessible within the cluster
      targetPort: {{ .Values.postgres.containerPort }} # Port PostgreSQL is listening on in the container