apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: qmessentials
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: {{ .Values.postgres.containerPort }}
        env:
        - name: POSTGRES_DB
          value: auth_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-postgres-secret
              key: AUTH_POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: auth-postgres-secret
              key: AUTH_POSTGRES_PASSWORD  
        volumeMounts:
        - name: auth-postgres-storage
          mountPath: {{ .Values.postgres.storage.mountPath }}
      volumes:
      - name: auth-postgres-storage
        persistentVolumeClaim:
          claimName: auth-postgres-pvc  
