apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: qmessentials
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
    [INPUT]
        Name        tail
        Path        /var/log/containers/*.log
        Parser      docker
        Tag         kube.*
    [OUTPUT]
        Name        es
        Match       *
        Host        opensearch.qmessentials.svc.cluster.local
        Port        9200
        Index       kubernetes_logs
        Type        _doc
    [FILTER]
        Name        kubernetes
        Match       kube.*
