apiVersion: v1
kind: Service
metadata:
  name: opensearch-cluster
  namespace: qmessentials
  labels:
    app: opensearch
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: opensearch
  ports:
    - protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      name: http
    - protocol: TCP
      port: {{ .Values.service.transportPort }}
      targetPort: {{ .Values.service.transportPort }}
      name: transport
  type: {{ .Values.service.type }}
