apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-pv
  namespace: qmessentials
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath }}
