apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: qmessentials
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qmessentials
      service: auth
  template:
    metadata:
      labels:
        app: qmessentials
        service: auth
    spec:
      containers:
      - name: qmessentials-auth
        image: qmessentials/auth:0.1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3010
        env:
        - name: PORT
          value: 3010
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-postgres-secret
              key: AUTH_POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-postgres-secret
              key: AUTH_POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: auth_db