apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: qmessentials
spec:
  selector:
    app: auth-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort