apiVersion: v1
kind: Service
metadata:
  name: qmessentials-auth-service
  namespace: qmessentials
spec:
  selector:
    app: qmessentials
    service: auth
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # External port
      targetPort: {{ .Values.service.port }}  # Container port
  type: {{ .Values.service.type }}
