apiVersion: v1
kind: Service
metadata:
  name: opensearch-cluster
  namespace: qmessentials
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: http
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: transport
  type: ClusterIP
